
	MODULE CONSTANTS
	
	IMPLICIT NONE
	DOUBLE PRECISION, PARAMETER :: PI = 4.D0*ATAN(1.D0)
	DOUBLE PRECISION, PARAMETER :: SMALL_NUM = 1.0E-16

	CONTAINS
	
	FUNCTION CROSSPRDCT(XX,YY)

	IMPLICIT NONE

	DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: XX, YY
	DOUBLE PRECISION, DIMENSION(3) :: CROSSPRDCT

	CROSSPRDCT(1) = XX(2)*YY(3) - XX(3)*YY(2)
	CROSSPRDCT(2) = XX(3)*YY(1) - XX(1)*YY(3)
	CROSSPRDCT(3) = XX(1)*YY(2) - XX(2)*YY(1)
	
	END FUNCTION
	
	END MODULE CONSTANTS
